apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  labels:
    app: nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Terraform & EKS</title>
    </head>
    <body>
        <h1>This HTML page is created from Terraform & EKS Modules</h1>
    </body>
    </html>
