apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-html-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-html-app
  template:
    metadata:
      labels:
        app: simple-html-app
    spec:
      containers:
        - name: simple-html-app
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/terraform-ecr-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
