apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 941377156271.dkr.ecr.ap-south-1.amazonaws.com/ecr-repo:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-html-volume
          configMap:
            name: nginx-html
